"""empty message

Revision ID: 51a77bfc38e8
Revises: df2d103d1e20
Create Date: 2023-11-28 00:07:19.773174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51a77bfc38e8'
down_revision = 'df2d103d1e20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('favorite_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('favorite_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
