"""empty message

Revision ID: df2d103d1e20
Revises: 5de70af99d6d
Create Date: 2023-11-27 23:46:32.701048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df2d103d1e20'
down_revision = '5de70af99d6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('favorite_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('favorite_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
